import React from "react";
import { Noto_Sans, Nunito_Sans } from "next/font/google";
import "./globals.css";

// Specify the font weight for Noto Sans (e.g., 400 for regular)
const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-noto"
});
const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-nunito"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  // Combine font classes into a single string
  const combinedFontClasses = `${notoSans.variable} ${nunito.variable}`;

  return (
    <html lang="en" className={combinedFontClasses}>
      <head>
        {/* Include font styles */}
        <meta charSet="UTF-8" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add other meta tags, CSS links, and scripts here */}
      </head>
      <body className={notoSans.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
