import React from 'react';
import { Noto_Sans } from 'next/font/google';
import './globals.css';

// Specify the font weight for Noto Sans (e.g., 400 for regular)
const notoSans = Noto_Sans({subsets:["latin"] ,   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        {/* Include font styles */}
        <style>{notoSans.styles}</style>
        <meta charSet="UTF-8" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add other meta tags, CSS links, and scripts here */}
      </head>
      <body className={notoSans.className}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
